### ISSUE TITLE
Change target NTP server configuration changes 

### ISSUE THREAD

**Issue by paulelong** [Microsoft/Windows-Time-Calibration-Tools#16]
Targeting an IP address is preferable in many instances. The friendly name might also be important, but there could be multiple addresses. This change is to allow the configuration to include:
[Name]
IPAddress : REG_SZ
Expected DNS Name: REG_SZ
Polling Frequency: REG_DWORD
Where [Name] is a friendly user defined name for the monitoring target.

**Comment by Alan-Jowett** [comment]
No longer required
